export const ROLE_TESTER_ADVANCED = "TESTER_ADVANCED";
export const ROLE_TESTER_INTERMEDIARY = "TESTER_INTERMEDIARY";
export const ROLE_TESTER_BASIC = "TESTER_BASIC";
export const ROLE_ADMINISTRATOR = "ADMINISTRATOR";
